/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.83
 * Generated at: 2023-01-18 07:25:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class productDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("jar:file:/C:/_Spring/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Yproject/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/../views/includes/admin/footer.jsp", Long.valueOf(1673427845690L));
    _jspx_dependants.put("jar:file:/C:/_Spring/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Yproject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1667532381377L));
    _jspx_dependants.put("jar:file:/C:/_Spring/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Yproject/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/../views/includes/admin/header.jsp", Long.valueOf(1673851631790L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \r\n");
      out.write("    \r\n");
      out.write("       \r\n");
      out.write("     \r\n");
      out.write("     \r\n");
      out.write("     \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write(" \r\n");
      out.write("  <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\r\n");
      out.write("  <title>상품 정보</title>\r\n");
      out.write("  <!-- Font Awesome -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.11.2/css/all.css\">\r\n");
      out.write("  <!-- Bootstrap core CSS -->\r\n");
      out.write("  <link href=\"../resources/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <!-- Material Design Bootstrap -->\r\n");
      out.write("  <link href=\"../resources/css/mdb.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <!-- Your custom styles (optional) -->\r\n");
      out.write("  <link href=\"../resources/css/style.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../resources/css/productDetail.css\">\r\n");
      out.write("  <style type=\"text/css\">\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body style=\"background-color : #A9A9A9;\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("       \r\n");
      out.write("\r\n");
      out.write("<style>\n");
      out.write(".green-text{\r\n");
      out.write("font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write(".navbar-nav nav-flex-icons{\r\n");
      out.write("float: right;\r\n");
      out.write("}\r\n");
      out.write(".nav-item{\r\n");
      out.write("margin-left: 10px;\r\n");
      out.write("}\r\n");
      out.write(".nav-link{\r\n");
      out.write("margin-left: 5px;\r\n");
      out.write("}\r\n");
      out.write("\n");
      out.write("</style>\r\n");
      out.write("  <!-- Navbar -->\r\n");
      out.write("  <nav class=\"navbar fixed-top navbar-expand-lg navbar-light white\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("      <!-- Brand -->\r\n");
      out.write("      <a class=\"navbar-brand\" href=\"/main\" >\r\n");
      out.write("        <strong class=\"green-text\" style=\"color:#1E3932;\">StarCoffee</strong>\r\n");
      out.write("      </a>\r\n");
      out.write("\r\n");
      out.write("      <!-- Collapse -->\r\n");
      out.write("      <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\"\r\n");
      out.write("        aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("        <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("      </button>\r\n");
      out.write("\r\n");
      out.write("      <!-- Links -->\r\n");
      out.write("      <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("		\r\n");
      out.write("		<!-- Left -->\r\n");
      out.write("        <ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("         \r\n");
      out.write("        </ul>\r\n");
      out.write("       \r\n");
      out.write("        <!-- Right -->\r\n");
      out.write("        <ul class=\"navbar-nav nav-flex-icons\">\r\n");
      out.write("          \r\n");
      out.write("         \r\n");
      out.write("           ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("           	");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write(" \r\n");
      out.write("           \r\n");
      out.write("        </ul>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav>\r\n");
      out.write("  <!-- Navbar -->\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<script>\r\n");
      out.write("/* gnb_area 로그아웃 버튼 작동 */\r\n");
      out.write("$(\"#gnb_logout_button\").click(function(){\r\n");
      out.write(" //   alert(\"버튼 작동\");\r\n");
      out.write("    $.ajax({\r\n");
      out.write("        type:\"POST\",\r\n");
      out.write("        url:\"/member/logout.do\",\r\n");
      out.write("        success:function(data){\r\n");
      out.write("        //    alert(\"로그아웃 성공\");\r\n");
      out.write("            document.location.reload();     \r\n");
      out.write("        } \r\n");
      out.write("    }); // ajax \r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("  <!--Main layout-->\r\n");
      out.write("  <main >\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("        <!--Grid row-->\r\n");
      out.write("        <div class=\"row wow fadeIn content_top\">\r\n");
      out.write("        <div class=\"ct_left_area\">\r\n");
      out.write("        	<div class=\"image_wrap\" data-productid=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productIntro.imageList[0].productId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" data-path=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productIntro.imageList[0].uploadPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" data-uuid=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productIntro.imageList[0].uuid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" data-filename=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productIntro.imageList[0].fileName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("        		<img>\r\n");
      out.write("        	</div>\r\n");
      out.write("        </div> \r\n");
      out.write("        <div class=\"ct_right_area\">\r\n");
      out.write("        	<div class=\"title\">\r\n");
      out.write("        		<h1>\r\n");
      out.write("        			");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productIntro.productName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("        		</h1>\r\n");
      out.write("        	</div>\r\n");
      out.write("        	<div class=\"line\"></div>\r\n");
      out.write("        	\r\n");
      out.write("        	<div class=\"price\">\r\n");
      out.write("        		<div class=\"discount_price\">\r\n");
      out.write("        			<span class=\"discount_price_number\">");
      if (_jspx_meth_fmt_005fformatNumber_005f2(_jspx_page_context))
        return;
      out.write("</span>\r\n");
      out.write("        		</div>\r\n");
      out.write("        		<div>\r\n");
      out.write("        			예상 적립 포인트 : <span class=\"point_span\"></span>원\r\n");
      out.write("        		</div>\r\n");
      out.write("        	</div>\r\n");
      out.write("        	<div class=\"line\"></div>\r\n");
      out.write("        	<div class=\"button\">\r\n");
      out.write("        		<div class=\"button_quantity\">\r\n");
      out.write("        			수량\r\n");
      out.write("        			<input type=\"text\" class=\"quantity_input\" value=\"1\">\r\n");
      out.write("        			<span>\r\n");
      out.write("        				<button class=\"plus_btn\">+</button>\r\n");
      out.write("        				<button class=\"minus_btn\">-</button>\r\n");
      out.write("        			</span>\r\n");
      out.write("        		</div>\r\n");
      out.write("        		\r\n");
      out.write("        		<div class=\"button_set\">\r\n");
      out.write("        			<a class=\"btn_cart\"><span>장바구니 담기</span></a>\r\n");
      out.write("        			<a class=\"btn_buy\"><span>바로구매</span></a>\r\n");
      out.write("        		</div>\r\n");
      out.write("        	</div>\r\n");
      out.write("        	\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("		 \r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <!--Grid row-->\r\n");
      out.write("        <div class=\"line\"></div>\r\n");
      out.write("		<div class=\"content_middle\">\r\n");
      out.write("			<div class=\"product_intro\">\r\n");
      out.write("				");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productIntro.productInfo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"line\"></div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"content_bottom\">\r\n");
      out.write("                   					\r\n");
      out.write("                   					<div class=\"reply_subject\">\r\n");
      out.write("		                   					<h2>Review</h2>\r\n");
      out.write("                   					</div>\r\n");
      out.write("                   					\r\n");
      out.write("                   					<div class=\"reply_not_div\">\r\n");
      out.write("					\r\n");
      out.write("									</div>\r\n");
      out.write("									<ul class=\"reply_content_ul\">\r\n");
      out.write("											\r\n");
      out.write("									</ul>\r\n");
      out.write("									<div class=\"reply_pageInfo_div\">\r\n");
      out.write("										<ul class=\"pageMaker\">\r\n");
      out.write("										\r\n");
      out.write("										</ul>\r\n");
      out.write("\r\n");
      out.write("									</div>\r\n");
      out.write("                   					");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                   					\r\n");
      out.write("                   				</div>\r\n");
      out.write("     \r\n");
      out.write("     <!-- 주문 form -->\r\n");
      out.write("	<form action=\"/order/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.memberId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" method=\"get\" class=\"order_form\">\r\n");
      out.write("		<input type=\"hidden\" name=\"orders[0].productId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productIntro.productId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("		<input type=\"hidden\" name=\"orders[0].productCount\" value=\"\">\r\n");
      out.write("	</form>\r\n");
      out.write("     \r\n");
      out.write("    </div>\r\n");
      out.write("  </main>\r\n");
      out.write("  <!--Main layout-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!--Footer-->\r\n");
      out.write("  <footer class=\"page-footer text-center font-small mt-4 wow fadeIn\">\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <!--/.Call to action-->\r\n");
      out.write("\r\n");
      out.write("    <hr class=\"my-4\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Social icons -->\r\n");
      out.write("    <div class=\"pb-4\">\r\n");
      out.write("      <a href=\"https://www.facebook.com/mdbootstrap\" target=\"_blank\">\r\n");
      out.write("        <i class=\"fab fa-facebook-f mr-3\"></i>\r\n");
      out.write("      </a>\r\n");
      out.write("\r\n");
      out.write("      <a href=\"https://twitter.com/MDBootstrap\" target=\"_blank\">\r\n");
      out.write("        <i class=\"fab fa-twitter mr-3\"></i>\r\n");
      out.write("      </a>\r\n");
      out.write("\r\n");
      out.write("      <a href=\"https://www.youtube.com/watch?v=7MUISDJ5ZZ4\" target=\"_blank\">\r\n");
      out.write("        <i class=\"fab fa-youtube mr-3\"></i>\r\n");
      out.write("      </a>\r\n");
      out.write("\r\n");
      out.write("      <a href=\"https://plus.google.com/u/0/b/107863090883699620484\" target=\"_blank\">\r\n");
      out.write("        <i class=\"fab fa-google-plus-g mr-3\"></i>\r\n");
      out.write("      </a>\r\n");
      out.write("\r\n");
      out.write("      <a href=\"https://dribbble.com/mdbootstrap\" target=\"_blank\">\r\n");
      out.write("        <i class=\"fab fa-dribbble mr-3\"></i>\r\n");
      out.write("      </a>\r\n");
      out.write("\r\n");
      out.write("      <a href=\"https://pinterest.com/mdbootstrap\" target=\"_blank\">\r\n");
      out.write("        <i class=\"fab fa-pinterest mr-3\"></i>\r\n");
      out.write("      </a>\r\n");
      out.write("\r\n");
      out.write("      <a href=\"https://github.com/mdbootstrap/bootstrap-material-design\" target=\"_blank\">\r\n");
      out.write("        <i class=\"fab fa-github mr-3\"></i>\r\n");
      out.write("      </a>\r\n");
      out.write("\r\n");
      out.write("      <a href=\"http://codepen.io/mdbootstrap/\" target=\"_blank\">\r\n");
      out.write("        <i class=\"fab fa-codepen mr-3\"></i>\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Social icons -->\r\n");
      out.write("\r\n");
      out.write("    <!--Copyright-->\r\n");
      out.write("    <div class=\"footer-copyright py-3\">\r\n");
      out.write("      © 2022 - 2023 Copyright : Kim Young Hwan\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--/.Copyright-->\r\n");
      out.write("\r\n");
      out.write("  </footer>\r\n");
      out.write("  <!--/.Footer-->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- SCRIPTS -->\r\n");
      out.write("  <!-- JQuery -->\r\n");
      out.write("  <script type=\"text/javascript\" src=\"../resources/js/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("  <!-- Bootstrap tooltips -->\r\n");
      out.write("  <script type=\"text/javascript\" src=\"../resources/js/popper.min.js\"></script>\r\n");
      out.write("  <!-- Bootstrap core JavaScript -->\r\n");
      out.write("  <script type=\"text/javascript\" src=\"../resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("  <!-- MDB core JavaScript -->\r\n");
      out.write("  <script type=\"text/javascript\" src=\"../resources/js/mdb.min.js\"></script>\r\n");
      out.write("  <!-- Initializations -->\r\n");
      out.write("  <script>\r\n");
      out.write("    // Animations initialization\r\n");
      out.write("    new WOW().init();\r\n");
      out.write("    \r\n");
      out.write("    //댓글 페이지 정보\r\n");
      out.write("	  const pcri ={\r\n");
      out.write("			  productId : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productIntro.productId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("',\r\n");
      out.write("			  productPageNum : 1,\r\n");
      out.write("			  productAmount : 10\r\n");
      out.write("			  \r\n");
      out.write("	  }\r\n");
      out.write("    \r\n");
      out.write("    $(document).ready(function(){\r\n");
      out.write("    	\r\n");
      out.write("    	// 리뷰 리스트 출력 \r\n");
      out.write("      	const productId = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productIntro.productId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("      	\r\n");
      out.write("      	$.getJSON(\"/reply/list\", {productId : productId}, function(obj){\r\n");
      out.write("      		\r\n");
      out.write("      		if(obj.list.length === 0){\r\n");
      out.write("      			$(\".reply_not_div\").html('<span>아직 작성된 리뷰가 없습니다.</span>');\r\n");
      out.write("      			$(\".reply_content_ul\").html('');\r\n");
      out.write("      			$(\".pageMaker\").html('');\r\n");
      out.write("      		}else{\r\n");
      out.write("      			\r\n");
      out.write("      			$(\".reply_not_div\").html('');\r\n");
      out.write("      			\r\n");
      out.write("      			const  list = obj.list;\r\n");
      out.write("      			const pf = obj.pageInfo;\r\n");
      out.write("      			const userId = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.memberId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("      			\r\n");
      out.write("      			//list\r\n");
      out.write("      			\r\n");
      out.write("      			let reply_list = '';\r\n");
      out.write("      			\r\n");
      out.write("      			$(list).each(function(i,obj){\r\n");
      out.write("      				reply_list += '<li>';\r\n");
      out.write("      				reply_list += '<div class=\"comment_wrap\">';\r\n");
      out.write("      				\r\n");
      out.write("      				reply_list += '<div class=\"reply_top\">';\r\n");
      out.write("    				/* 아이디 */\r\n");
      out.write("    				reply_list += '<span class=\"id_span\">'+ obj.memberId+'</span>';\r\n");
      out.write("    				\r\n");
      out.write("    				/* 평점 */\r\n");
      out.write("    				reply_list += '<span class=\"rating_span\">평점 : <span class=\"rating_value_span\">'+ obj.rating +'</span>점</span>';\r\n");
      out.write("    				if(obj.memberId === userId){\r\n");
      out.write("    					reply_list += '<a class=\"update_reply_btn\" href=\"'+ obj.replyId +'\">수정</a><a class=\"delete_reply_btn\" href=\"'+ obj.replyId +'\">삭제</a>';\r\n");
      out.write("    				}\r\n");
      out.write("    				reply_list += '</div>';\r\n");
      out.write("    				reply_list += '<div class=\"reply_bottom\">';\r\n");
      out.write("    				reply_list += '<div class=\"reply_bottom_txt\">'+ obj.content +'</div>';\r\n");
      out.write("    				reply_list += '</div>';\r\n");
      out.write("    				reply_list += '</div>';\r\n");
      out.write("    				reply_list += '</li>';\r\n");
      out.write("      			});\r\n");
      out.write("      			\r\n");
      out.write("      			$(\".reply_content_ul\").html(reply_list);\r\n");
      out.write("      			\r\n");
      out.write("      			//페이지 버튼\r\n");
      out.write("      			\r\n");
      out.write("      			let reply_pageMaker = '';\r\n");
      out.write("      			/* prev */\r\n");
      out.write("				if(pf.prev){\r\n");
      out.write("					let prev_num = pf.pageStart -1;\r\n");
      out.write("					reply_pageMaker += '<li class=\"pageMaker_btn prev\">';\r\n");
      out.write("					reply_pageMaker += '<a href=\"'+ prev_num +'\">이전</a>';\r\n");
      out.write("					reply_pageMaker += '</li>';	\r\n");
      out.write("				}\r\n");
      out.write("				/* number btn */\r\n");
      out.write("				for(let i = pf.pageStart; i < pf.pageEnd+1; i++){\r\n");
      out.write("					reply_pageMaker += '<li class=\"pageMaker_btn ';\r\n");
      out.write("					if(pf.pcri.productPageNum === i){\r\n");
      out.write("						reply_pageMaker += 'active';\r\n");
      out.write("					}\r\n");
      out.write("					reply_pageMaker += '\">';\r\n");
      out.write("					reply_pageMaker += '<a href=\"'+i+'\">'+i+'</a>';\r\n");
      out.write("					reply_pageMaker += '</li>';\r\n");
      out.write("				}\r\n");
      out.write("				/* next */\r\n");
      out.write("				if(pf.next){\r\n");
      out.write("					let next_num = pf.pageEnd +1;\r\n");
      out.write("					reply_pageMaker += '<li class=\"pageMaker_btn next\">';\r\n");
      out.write("					reply_pageMaker += '<a href=\"'+ next_num +'\">다음</a>';\r\n");
      out.write("					reply_pageMaker += '</li>';	\r\n");
      out.write("				}	\r\n");
      out.write("				\r\n");
      out.write("				$(\".pageMaker\").html(reply_pageMaker);\r\n");
      out.write("      		}\r\n");
      out.write("      		\r\n");
      out.write("      	});\r\n");
      out.write("    	\r\n");
      out.write("    	 /* 이미지 삽입 */\r\n");
      out.write("	const bobj = $(\".image_wrap\");\r\n");
      out.write("    		\r\n");
      out.write("    	 \r\n");
      out.write("    	 if(bobj.data(\"productid\")){\r\n");
      out.write("    	\r\n");
      out.write("    		const uploadPath = bobj.data(\"path\");\r\n");
      out.write("    		console.log(uploadPath);\r\n");
      out.write("    		const uuid = bobj.data(\"uuid\");\r\n");
      out.write("    		const fileName = bobj.data(\"filename\");\r\n");
      out.write("    		\r\n");
      out.write("    		const fileCallPath = encodeURIComponent(uploadPath.replace(/\\\\/g, '/')  + \"/\" + uuid + \"_\" + fileName);\r\n");
      out.write("    		\r\n");
      out.write("    		bobj.find(\"img\").attr('src','/display?fileName=' + fileCallPath);\r\n");
      out.write("    	 }else{\r\n");
      out.write("    		 bobj.find(\"img\").attr('src','/resources/img/non_image2.png');\r\n");
      out.write("    	 }\r\n");
      out.write("\r\n");
      out.write("    	//포인트\r\n");
      out.write("    	    let productPrice = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productIntro.productPrice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("    	    let point = productPrice*0.05;\r\n");
      out.write("    	    point = Math.floor(point);\r\n");
      out.write("    	    $(\".point_span\").text(point);\r\n");
      out.write("    	    \r\n");
      out.write("    	//리뷰 리스트 출력\r\n");
      out.write("    	\r\n");
      out.write("    	\r\n");
      out.write("    	\r\n");
      out.write("    	$.getJSON(\"/reply/list\", {productId : productId}, function(obj){\r\n");
      out.write("    		\r\n");
      out.write("    		makeReplyContent(obj);\r\n");
      out.write("    		\r\n");
      out.write("    	});\r\n");
      out.write("    	    \r\n");
      out.write("    	 \r\n");
      out.write("    }); //$(document).ready\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    //수량 버튼 조작\r\n");
      out.write("    let quantity = $(\".quantity_input\").val();\r\n");
      out.write("    $(\".plus_btn\").on(\"click\",function(){\r\n");
      out.write("    	$(\".quantity_input\").val(++quantity);\r\n");
      out.write("    	\r\n");
      out.write("    });\r\n");
      out.write("    $(\".minus_btn\").on(\"click\",function(){\r\n");
      out.write("    	if(quantity > 1 ){    		\r\n");
      out.write("    	$(\".quantity_input\").val(--quantity);\r\n");
      out.write("    	}\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    //서버로 전송할 데이터\r\n");
      out.write("    const form = {\r\n");
      out.write("    		memberId : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.memberId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("',\r\n");
      out.write("    		productId : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productIntro.productId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("',\r\n");
      out.write("    		productCount : ''\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    //장바구니 추가 버튼\r\n");
      out.write("    $(\".btn_cart\").on(\"click\", function(e){\r\n");
      out.write("    	form.productCount = $(\".quantity_input\").val();\r\n");
      out.write("    	$.ajax({\r\n");
      out.write("    		url : '/cart/add',\r\n");
      out.write("    		type : 'POST',\r\n");
      out.write("    		data : form,\r\n");
      out.write("    		success: function(result){\r\n");
      out.write("    			cartAlert(result);\r\n");
      out.write("    		}\r\n");
      out.write("    	})\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    function cartAlert(result){\r\n");
      out.write("		if(result == '0'){\r\n");
      out.write("			alert(\"장바구니에 추가를 하지 못하였습니다.\");\r\n");
      out.write("		} else if(result == '1'){\r\n");
      out.write("			alert(\"장바구니에 추가되었습니다.\");\r\n");
      out.write("		} else if(result == '2'){\r\n");
      out.write("			alert(\"장바구니에 이미 추가되어져 있습니다.\");\r\n");
      out.write("		} else if(result == '5'){\r\n");
      out.write("			alert(\"로그인이 필요합니다.\");	\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("    \r\n");
      out.write("    //바로구매 버튼\r\n");
      out.write("    $(\".btn_buy\").on(\"click\", function(){\r\n");
      out.write("    	let productCount = $(\".quantity_input\").val();\r\n");
      out.write("    	console.log(productCount);\r\n");
      out.write("    	$(\".order_form\").find(\"input[name='orders[0].productCount']\").val(productCount);\r\n");
      out.write("    	$(\".order_form\").submit();\r\n");
      out.write("    \r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("  //리뷰 쓰기\r\n");
      out.write("    $(\".reply_button_wrap\").on(\"click\", function(e){\r\n");
      out.write("    	\r\n");
      out.write("    	e.preventDefault();\r\n");
      out.write("    	\r\n");
      out.write("    	const memberId = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.memberId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("    	const productId = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productIntro.productId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("    	\r\n");
      out.write("    	$.ajax({\r\n");
      out.write("    		data : {\r\n");
      out.write("    			productId : productId,\r\n");
      out.write("    			memberId : memberId\r\n");
      out.write("    		},\r\n");
      out.write("    		url : '/reply/check',\r\n");
      out.write("    		type : 'POST',\r\n");
      out.write("    		success : function(result){\r\n");
      out.write("    			\r\n");
      out.write("    			if(result == '1'){\r\n");
      out.write("    				alert(\"이미 등록된 리뷰가 존재합니다.\")\r\n");
      out.write("    			}else if(result === '0'){\r\n");
      out.write("    				let popUrl = \"/replyEnroll/\" + memberId + \"?productId=\" + productId;\r\n");
      out.write("    				console.log(popUrl);\r\n");
      out.write("    				let popOption = \"width = 490px, height=490px, top=300px , left=300px, scrollbars=yes\"\r\n");
      out.write("    			\r\n");
      out.write("    				window.open(popUrl,\"리뷰 작성\", popOption);\r\n");
      out.write("    			}\r\n");
      out.write("    		}\r\n");
      out.write("    	});\r\n");
      out.write("    	\r\n");
      out.write("    });\r\n");
      out.write("  \r\n");
      out.write("  //댓글 데이터 서버 요청 및 댓글 동적 생성 메서드\r\n");
      out.write("  let replyListInit = function(){\r\n");
      out.write("	  $.getJSON (\"/reply/list\", pcri , function(obj){\r\n");
      out.write("		  makeReplyContent(obj);\r\n");
      out.write("	  });\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  //리뷰 수정 버튼\r\n");
      out.write("  $(document).on('click', '.update_reply_btn', function(e){\r\n");
      out.write("	 \r\n");
      out.write("	  e.preventDefault();\r\n");
      out.write("	  let replyId = $(this).attr(\"href\");\r\n");
      out.write("	  let popUrl = \"/replyUpdate?replyId=\" + replyId + \"&productId=\" + '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productIntro.productId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' +  \"&memberId=\" + '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.memberId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("	  let popOption = \"width = 490px , height=490px, top=300px , left=300px, scrollbars=yes\"\r\n");
      out.write(" \r\n");
      out.write("  		window.open(popUrl, \"리뷰 수정\", popOption);\r\n");
      out.write("  });\r\n");
      out.write("  \r\n");
      out.write("  //리뷰 삭제 버튼\r\n");
      out.write("  $(document).on('click', '.delete_reply_btn', function(e){\r\n");
      out.write("	 e.preventDefault();\r\n");
      out.write("	 let replyId = $(this).attr(\"href\");\r\n");
      out.write("	 \r\n");
      out.write("	 $.ajax({\r\n");
      out.write("		 data : {\r\n");
      out.write("			 replyId : replyId,\r\n");
      out.write("			productId : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productIntro.productId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\r\n");
      out.write("		 },\r\n");
      out.write("		 url : '/reply/delete',\r\n");
      out.write("		 type: 'POST',\r\n");
      out.write("		 success : function(result){\r\n");
      out.write("			 replyListInit();\r\n");
      out.write("			 alert('리뷰를 삭제했습니다.');\r\n");
      out.write("		 }\r\n");
      out.write("	 });\r\n");
      out.write("  });\r\n");
      out.write("  // 댓글 동적 생성 메서드\r\n");
      out.write("  function makeReplyContent(obj){\r\n");
      out.write("	  \r\n");
      out.write("	  if(obj.list.length === 0 ){\r\n");
      out.write("		  $(\".reply_not_div\").html('<span>리뷰가 없습니다. </span>');\r\n");
      out.write("		  $(\".reply_content_ul\").html('');\r\n");
      out.write("		  $(\".pageMaker\").html('');\r\n");
      out.write("		  \r\n");
      out.write("	  }else {\r\n");
      out.write("		  \r\n");
      out.write("		  $(\".reply_not_div\").html('');\r\n");
      out.write("		  \r\n");
      out.write("		  const list = obj.list;\r\n");
      out.write("		  const pf = obj.pageInfo;\r\n");
      out.write("		  const userId = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.memberId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("		  \r\n");
      out.write("		  //list\r\n");
      out.write("		  \r\n");
      out.write("		  let reply_list = '';\r\n");
      out.write("		  \r\n");
      out.write("		  $(list).each(function(i,obj){\r\n");
      out.write("			 \r\n");
      out.write("			  reply_list += '<li>';\r\n");
      out.write("			  reply_list += '<div class=\"comment_wrap\">';\r\n");
      out.write("			  reply_list += '<div class=\"reply_top\">';\r\n");
      out.write("			  \r\n");
      out.write("			  //아이디\r\n");
      out.write("			  reply_list += '<span class=\"id_span\">' + obj.memberId+'</span>';\r\n");
      out.write("			 \r\n");
      out.write("			  //평점\r\n");
      out.write("			  reply_list += '<span class = \"rating_span\"> 평점 : <span class=\"rating_value_span\">'+ obj.rating +'</span>점</span>';\r\n");
      out.write("		  \r\n");
      out.write("		  	 if(obj.memberId === userId){\r\n");
      out.write("		  		 reply_list += '<a class=\"update_reply_btn\" href=\"'+obj.replyId + '\">수정 </a><a class=\"delete_reply_btn\" href=\"'+ obj.replyId +'\">삭제</a>';\r\n");
      out.write("		  	 }\r\n");
      out.write("		  	 reply_list += '</div>'; \r\n");
      out.write("		  	 reply_list += '<div class=\"reply_bottom\">';\r\n");
      out.write("		  	 reply_list += '<div class=\"reply_bottom_txt\">' + obj.content + '</div>';\r\n");
      out.write("		  	 reply_list += '</div>';\r\n");
      out.write("		  	 reply_list += '</div>';\r\n");
      out.write("		  	 reply_list += '</li>';\r\n");
      out.write("		  });\r\n");
      out.write("		  \r\n");
      out.write("		  $(\".reply_content_ul\").html(reply_list);\r\n");
      out.write("		  \r\n");
      out.write("		  //페이지 버튼\r\n");
      out.write("		  \r\n");
      out.write("		  let reply_pageMaker = '';\r\n");
      out.write("		  \r\n");
      out.write("		  	//prev\r\n");
      out.write("		  	if(pf.prev){\r\n");
      out.write("		  		let prev_num = pf.pageStart -1 ;\r\n");
      out.write("		  		reply_pageMaker += '<li class=\"pageMaker_btn prev\">';\r\n");
      out.write("		  		reply_pageMaker += '<a href=\"'+ prev_num + '\">이전</a>';\r\n");
      out.write("		  		reply_pageMaker += '</li>';\r\n");
      out.write("		  	}\r\n");
      out.write("		  	//number btn	\r\n");
      out.write("		  	for(let i = pf.pageStart; i< pf.pageEnd+1; i++){\r\n");
      out.write("		  		reply_pageMaker += '<li class=\"pageMaker_btn ';\r\n");
      out.write("		  		if(pf.pcri.productPageNum === i){\r\n");
      out.write("		  			reply_pageMaker += 'active';	\r\n");
      out.write("		  		}\r\n");
      out.write("		  		reply_pageMaker += '\">';\r\n");
      out.write("		  		reply_pageMaker += '<a href=\"'+i+ '\">'+i+'</a>';\r\n");
      out.write("		  		reply_pageMaker += '</li>';\r\n");
      out.write("		  		\r\n");
      out.write("		  	}\r\n");
      out.write("		  	\r\n");
      out.write("		  	// next \r\n");
      out.write("		  	if(pf.next){\r\n");
      out.write("		  		let next_num = pf.pageEnd +1;\r\n");
      out.write("		  		reply_pageMaker += '<li class=\"pageMaker_btn next\">';\r\n");
      out.write("		  		reply_pageMaker += '<a href=\"' + next_num + '\"> 다음 </a>';\r\n");
      out.write("		  		reply_pageMaker += '</li>';\r\n");
      out.write("		  	}\r\n");
      out.write("		  	\r\n");
      out.write("		  	$(\".pageMaker\").html(reply_pageMaker);\r\n");
      out.write("	  }\r\n");
      out.write("	  \r\n");
      out.write("	 \r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  	\r\n");
      out.write("  </script>\r\n");
      out.write("  \r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/../views/includes/admin/header.jsp(48,11) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("          <li class=\"nav-item\">\r\n");
          out.write("          \r\n");
          out.write("            <a href=\"/member/login\" class=\"nav-link border\">\r\n");
          out.write("             LogIn\r\n");
          out.write("            </a>\r\n");
          out.write("          </li>\r\n");
          out.write("          <li class=\"nav-item\">\r\n");
          out.write("            <a href=\"/member/join\" class=\"nav-link border\"\r\n");
          out.write("              >\r\n");
          out.write("             Join us\r\n");
          out.write("            </a>\r\n");
          out.write("          </li>\r\n");
          out.write("           ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/../views/includes/admin/header.jsp(62,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member != null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" \r\n");
          out.write("           	\r\n");
          out.write("           	<li class=\"nav-item\">\r\n");
          out.write("            <a href=\"/cart/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.memberId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"nav-link waves-effect\">\r\n");
          out.write("              \r\n");
          out.write("              <i class=\"fas fa-shopping-cart\"></i>\r\n");
          out.write("              <span class=\"\"> Cart </span>\r\n");
          out.write("            </a>\r\n");
          out.write("          </li>\r\n");
          out.write("           	\r\n");
          out.write("           	\r\n");
          out.write("           		<div class=\"nav-link border\">\r\n");
          out.write("           			<span>충전 금액 : ");
          if (_jspx_meth_fmt_005fformatNumber_005f0(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write(" </span>\r\n");
          out.write("           			<span>포인트 : ");
          if (_jspx_meth_fmt_005fformatNumber_005f1(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("</span>\r\n");
          out.write("           		</div>\r\n");
          out.write("            ");
          if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("             <a href=\"/member/logout.do\" class=\"nav-link border border-light rounded waves-effect\">Logout</a>\r\n");
          out.write("            \r\n");
          out.write("           ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/../views/includes/admin/header.jsp(74,28) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.money}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/../views/includes/admin/header.jsp(74,28) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setPattern("#,###");
      int _jspx_eval_fmt_005fformatNumber_005f0 = _jspx_th_fmt_005fformatNumber_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f0);
      _jspx_th_fmt_005fformatNumber_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f1_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f1.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/../views/includes/admin/header.jsp(75,26) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.point }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/../views/includes/admin/header.jsp(75,26) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f1.setPattern("#,###");
      int _jspx_eval_fmt_005fformatNumber_005f1 = _jspx_th_fmt_005fformatNumber_005f1.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f1);
      _jspx_th_fmt_005fformatNumber_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f1, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/../views/includes/admin/header.jsp(77,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.adminCk == 1 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("            <a href=\"/admin/main\" class=\"nav-link border border-light rounded waves-effect\">AdminPage</a>\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f2 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f2_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f2.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f2.setParent(null);
      // /WEB-INF/views/productDetail.jsp(53,47) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productIntro.productPrice }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/productDetail.jsp(53,47) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f2.setPattern("#,###원");
      int _jspx_eval_fmt_005fformatNumber_005f2 = _jspx_th_fmt_005fformatNumber_005f2.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f2);
      _jspx_th_fmt_005fformatNumber_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f2, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /WEB-INF/views/productDetail.jsp(112,24) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member != null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                   					\r\n");
          out.write("                   					<div class=\"reply_button_wrap\">\r\n");
          out.write("                   						<button>리뷰 작성</button>\r\n");
          out.write("                   					</div>\r\n");
          out.write("                   					\r\n");
          out.write("                   					");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }
}
