/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.83
 * Generated at: 2023-01-12 06:30:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/C:/_Spring/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Yproject/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/_Spring/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Yproject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/member/../includes/admin/footer.jsp", Long.valueOf(1673427845690L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1667532381377L));
    _jspx_dependants.put("jar:file:/C:/_Spring/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Yproject/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("       \r\n");
      out.write("     \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("  <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\r\n");
      out.write("  <title>회원가입</title>\r\n");
      out.write("  <!-- Font Awesome -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.11.2/css/all.css\">\r\n");
      out.write("  <!-- Bootstrap core CSS -->\r\n");
      out.write("  <link href=\"../resources/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <!-- Material Design Bootstrap -->\r\n");
      out.write("  <link href=\"../resources/css/mdb.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <!-- Your custom styles (optional) -->\r\n");
      out.write("  <link href=\"../resources/css/style.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"../resources/css/member/join.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<style>\n");
      out.write("/* 중복아이디 존재하지 않는경우 */\r\n");
      out.write("	.id_input_re_1{\r\n");
      out.write("		color : green;\r\n");
      out.write("		display : none;\r\n");
      out.write("	}\r\n");
      out.write("	/* 중복아이디 존재하는 경우 */\r\n");
      out.write("	.id_input_re_2{\r\n");
      out.write("		color : red;\r\n");
      out.write("		display : none;\r\n");
      out.write("	}\r\n");
      out.write("	/* 유효성 검사 문구 */\r\n");
      out.write(" \r\n");
      out.write(".final_id_ck{\r\n");
      out.write("    display: none;\r\n");
      out.write("}\r\n");
      out.write(".final_pw_ck{\r\n");
      out.write("    display: none;\r\n");
      out.write("}\r\n");
      out.write(".final_pwck_ck{\r\n");
      out.write("    display: none;\r\n");
      out.write("}\r\n");
      out.write(".final_name_ck{\r\n");
      out.write("    display: none;\r\n");
      out.write("}\r\n");
      out.write(".final_mail_ck{\r\n");
      out.write("    display: none;\r\n");
      out.write("}\r\n");
      out.write(".final_addr_ck{\r\n");
      out.write("    display: none;\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write("/* 비밀번호 확인 일치 유효성검사 */\r\n");
      out.write(".pwck_input_re_1{\r\n");
      out.write("        color : green;\r\n");
      out.write("        display : none;    \r\n");
      out.write("}\r\n");
      out.write(".pwck_input_re_2{\r\n");
      out.write("        color : red;\r\n");
      out.write("        display : none;    \r\n");
      out.write("}    \r\n");
      out.write(" \n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<body class=\"grey lighten-3\">\r\n");
      out.write("\r\n");
      out.write("	<div class=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Navbar -->\r\n");
      out.write("   <!-- Navbar -->\r\n");
      out.write("  <nav class=\"navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("      <!-- Brand -->\r\n");
      out.write("      <a class=\"navbar-brand waves-effect\" href=\"/main\" >\r\n");
      out.write("        <strong class=\"green-text\">StarCoffee</strong>\r\n");
      out.write("      </a>\r\n");
      out.write("\r\n");
      out.write("      <!-- Collapse -->\r\n");
      out.write("      <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\"\r\n");
      out.write("        aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("        <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("      </button>\r\n");
      out.write("\r\n");
      out.write("      <!-- Links -->\r\n");
      out.write("      <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("		\r\n");
      out.write("		<!-- Left -->\r\n");
      out.write("        <ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("         \r\n");
      out.write("        </ul>\r\n");
      out.write("       \r\n");
      out.write("        <!-- Right -->\r\n");
      out.write("        <ul class=\"navbar-nav nav-flex-icons\">\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a href=\"/cart/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.memberId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"nav-link waves-effect\">\r\n");
      out.write("              \r\n");
      out.write("              <i class=\"fas fa-shopping-cart\"></i>\r\n");
      out.write("              <span class=\"clearfix d-none d-sm-inline-block\"> Cart </span>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("         \r\n");
      out.write("           ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("           	");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write(" \r\n");
      out.write("           \r\n");
      out.write("        </ul>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav>\r\n");
      out.write("  <!-- Navbar -->\r\n");
      out.write("\r\n");
      out.write("  <!--Main layout-->\r\n");
      out.write("  <main class=\"mt-5 pt-4\">\r\n");
      out.write("    <div class=\"container wow fadeIn\">\r\n");
      out.write("\r\n");
      out.write("      <!-- Heading -->\r\n");
      out.write("      <h2 class=\"my-5 h2 text-center\">회원가입</h2>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<form id=\"join_form\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("          <!--Card-->\r\n");
      out.write("          <div class=\"card\" >\r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("              <!--Grid row-->\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("				<div class=\"id_input_box md-form \">\r\n");
      out.write("					<input class=\"id_input form-control\" name=\"memberId\" placeholder=\"ID\">\r\n");
      out.write("						<span class=\"id_input_re_1\">사용 가능한 아이디입니다.</span>\r\n");
      out.write("						<span class=\"id_input_re_2\">아이디가 이미 존재합니다.</span>\r\n");
      out.write("						<span class=\"final_id_ck\">아이디를 입력해주세요.</span>\r\n");
      out.write("                 \r\n");
      out.write("				</div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <!--Grid row-->\r\n");
      out.write("\r\n");
      out.write("              <!--password-->\r\n");
      out.write("              <div class=\"md-form  pw_wrap\">\r\n");
      out.write("               \r\n");
      out.write("                <input type=\"password\" class=\"form-control  pw_input\" name=\"memberPw\" placeholder=\"Password\" >\r\n");
      out.write("             	<span class=\"final_pw_ck\">비밀번호를 입력해주세요.</span>\r\n");
      out.write("              </div>\r\n");
      out.write("              \r\n");
      out.write("              <!-- password check -->\r\n");
      out.write("              <div class=\"md-form input-group pwck_wrap \">\r\n");
      out.write("                \r\n");
      out.write("                <input type=\"password\" class=\" pwck_input\"  placeholder=\"비밀번호 확인\" >\r\n");
      out.write("              </div>\r\n");
      out.write("             	<span class=\"final_pwck_ck\">비밀번호 확인을 입력해주세요.</span>\r\n");
      out.write("             	<span class=\"pwck_input_re_1\">비밀번호가 일치합니다.</span>\r\n");
      out.write("                <span class=\"pwck_input_re_2\">비밀번호가 일치하지 않습니다.</span>\r\n");
      out.write("				\r\n");
      out.write("				<!--address-->\r\n");
      out.write("              <div class=\"md-form user_wrap\">\r\n");
      out.write("                <input type=\"text\" name=\"memberName\" class=\"form-control user_input\" placeholder=\"Name\">\r\n");
      out.write("                <span class=\"final_name_ck\">이름을 입력해주세요.</span>\r\n");
      out.write("              </div>\r\n");
      out.write("              \r\n");
      out.write("              \r\n");
      out.write("              <!--email-->\r\n");
      out.write("              <div class=\"md-form mail_wrap\">\r\n");
      out.write("             \r\n");
      out.write("                <input type=\"text\" id=\"email\" name=\"memberMail\" class=\"form-control mail_input\" placeholder=\"youremail@example.com\" style=\"\">\r\n");
      out.write("             \r\n");
      out.write("              </div>\r\n");
      out.write("                <div class=\"mail_check_wrap\">\r\n");
      out.write("					\r\n");
      out.write("						<input class=\"mail_check_input \" placeholder=\"인증번호\">\r\n");
      out.write("				 <button class=\"btn-secondary  mail_check_button\" type=\"button\">인증번호 전송</button>\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("						\r\n");
      out.write("					\r\n");
      out.write("					  \r\n");
      out.write("					<div class=\"clearfix\"></div>\r\n");
      out.write("					\r\n");
      out.write("				</div>\r\n");
      out.write("					<span id=\"mail_check_input_box_warn\"></span>\r\n");
      out.write("				<span class=\"final_mail_ck\">이메일을 입력해주세요.</span>\r\n");
      out.write("				<span class=\"mail_input_box_warn\"></span>\r\n");
      out.write("\r\n");
      out.write("              \r\n");
      out.write("             \r\n");
      out.write("          		<div class=\"address_button\" onclick=\"execution_daum_address()\">\r\n");
      out.write("						<button class=\"btn btn-secondary btn-md  \" type=\"button\">주소 찾기</button>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"address_wrap\">\r\n");
      out.write("					<div class=\"  address_input_box\">\r\n");
      out.write("                		<input type=\"text\" class=\"address_input_1\" name=\"memberAddr1\" readonly=\"readonly\">\r\n");
      out.write("							<div class=\"clearfix\"></div>\r\n");
      out.write("					</div>\r\n");
      out.write("              \r\n");
      out.write("              <!-- address-2 -->\r\n");
      out.write("             \r\n");
      out.write("               <div class=\"  address_input_box\">\r\n");
      out.write("            	    <input type=\"text\" class=\"address_input_2\" name=\"memberAddr2\" readonly=\"readonly\">						\r\n");
      out.write("			   </div>\r\n");
      out.write("             \r\n");
      out.write("					\r\n");
      out.write("               <div class=\"  address_input_box\">\r\n");
      out.write("            	    <input type=\"text\" class=\" address_input_3\" name=\"memberAddr3\" readonly=\"readonly\">						\r\n");
      out.write("					<span class=\"final_addr_ck\">상세 주소를 입력해주세요.</span>	\r\n");
      out.write("			   </div>\r\n");
      out.write("			   \r\n");
      out.write("\r\n");
      out.write("          </div>    \r\n");
      out.write("          <!--/.Card-->\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			<button class=\"btn btn-secondary  join_button\" type=\"button\">Join</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        </form>\r\n");
      out.write("        </div>\r\n");
      out.write("        </main>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("      \r\n");
      out.write("    \r\n");
      out.write("  \r\n");
      out.write("			");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!--Footer-->\r\n");
      out.write("  <footer class=\"page-footer text-center font-small mt-4 wow fadeIn\">\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <!--/.Call to action-->\r\n");
      out.write("\r\n");
      out.write("    <hr class=\"my-4\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Social icons -->\r\n");
      out.write("    <div class=\"pb-4\">\r\n");
      out.write("      <a href=\"https://www.facebook.com/mdbootstrap\" target=\"_blank\">\r\n");
      out.write("        <i class=\"fab fa-facebook-f mr-3\"></i>\r\n");
      out.write("      </a>\r\n");
      out.write("\r\n");
      out.write("      <a href=\"https://twitter.com/MDBootstrap\" target=\"_blank\">\r\n");
      out.write("        <i class=\"fab fa-twitter mr-3\"></i>\r\n");
      out.write("      </a>\r\n");
      out.write("\r\n");
      out.write("      <a href=\"https://www.youtube.com/watch?v=7MUISDJ5ZZ4\" target=\"_blank\">\r\n");
      out.write("        <i class=\"fab fa-youtube mr-3\"></i>\r\n");
      out.write("      </a>\r\n");
      out.write("\r\n");
      out.write("      <a href=\"https://plus.google.com/u/0/b/107863090883699620484\" target=\"_blank\">\r\n");
      out.write("        <i class=\"fab fa-google-plus-g mr-3\"></i>\r\n");
      out.write("      </a>\r\n");
      out.write("\r\n");
      out.write("      <a href=\"https://dribbble.com/mdbootstrap\" target=\"_blank\">\r\n");
      out.write("        <i class=\"fab fa-dribbble mr-3\"></i>\r\n");
      out.write("      </a>\r\n");
      out.write("\r\n");
      out.write("      <a href=\"https://pinterest.com/mdbootstrap\" target=\"_blank\">\r\n");
      out.write("        <i class=\"fab fa-pinterest mr-3\"></i>\r\n");
      out.write("      </a>\r\n");
      out.write("\r\n");
      out.write("      <a href=\"https://github.com/mdbootstrap/bootstrap-material-design\" target=\"_blank\">\r\n");
      out.write("        <i class=\"fab fa-github mr-3\"></i>\r\n");
      out.write("      </a>\r\n");
      out.write("\r\n");
      out.write("      <a href=\"http://codepen.io/mdbootstrap/\" target=\"_blank\">\r\n");
      out.write("        <i class=\"fab fa-codepen mr-3\"></i>\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Social icons -->\r\n");
      out.write("\r\n");
      out.write("    <!--Copyright-->\r\n");
      out.write("    <div class=\"footer-copyright py-3\">\r\n");
      out.write("      © 2022 - 2023 Copyright : Kim Young Hwan\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--/.Copyright-->\r\n");
      out.write("\r\n");
      out.write("  </footer>\r\n");
      out.write("  <!--/.Footer-->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("</div>\r\n");
      out.write("  <!--/.Footer-->\r\n");
      out.write("\r\n");
      out.write("  <!-- SCRIPTS -->\r\n");
      out.write("  <!-- JQuery -->\r\n");
      out.write("  <script type=\"text/javascript\" src=\"/resources/js/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("  <!-- Bootstrap tooltips -->\r\n");
      out.write("  <script type=\"text/javascript\" src=\"/resources/js/popper.min.js\"></script>\r\n");
      out.write("  <!-- Bootstrap core JavaScript -->\r\n");
      out.write("  <script type=\"text/javascript\" src=\"/resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("  <!-- MDB core JavaScript -->\r\n");
      out.write("  <script type=\"text/javascript\" src=\"/resources/js/mdb.min.js\"></script>\r\n");
      out.write("  <!-- Initializations -->\r\n");
      out.write("  <script src= \"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("  <script type=\"text/javascript\">\r\n");
      out.write("    // Animations initialization\r\n");
      out.write("    new WOW().init();\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    var code =\"\";\r\n");
      out.write("\r\n");
      out.write("    /* 유효성 검사 통과유무 변수 */\r\n");
      out.write("    var idCheck = false;            // 아이디\r\n");
      out.write("    var idckCheck = false;            // 아이디 중복 검사\r\n");
      out.write("    var pwCheck = false;            // 비번\r\n");
      out.write("    var pwckCheck = false;            // 비번 확인\r\n");
      out.write("    var pwckcorCheck = false;        // 비번 확인 일치 확인\r\n");
      out.write("    var nameCheck = false;            // 이름\r\n");
      out.write("    var mailCheck = false;            // 이메일\r\n");
      out.write("    var mailnumCheck = false;        // 이메일 인증번호 확인\r\n");
      out.write("    var addressCheck = false         // 주소\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    $(document).ready(function(){\r\n");
      out.write("    	//회원가입 버튼(회원가입 기능 작동)\r\n");
      out.write("    	$(\".join_button\").click(function(){\r\n");
      out.write("    		\r\n");
      out.write("    		/*입력값 변수*/\r\n");
      out.write("    	var id = $('.id_input').val();\r\n");
      out.write("    	var pw = $('.pw_input').val();\r\n");
      out.write("    	var pwck = $('.pwck_input').val();\r\n");
      out.write("    	var name = $('.user_input').val();\r\n");
      out.write("    	var mail = $('.mail_input').val();\r\n");
      out.write("    	var addr = $('.address_input_3').val();\r\n");
      out.write("    	\r\n");
      out.write("    	   /* 아이디 유효성검사 */\r\n");
      out.write("        if(id == \"\"){\r\n");
      out.write("            $('.final_id_ck').css('display','block');\r\n");
      out.write("            idCheck = false;\r\n");
      out.write("        }else{\r\n");
      out.write("            $('.final_id_ck').css('display', 'none');\r\n");
      out.write("            idCheck = true;\r\n");
      out.write("        }\r\n");
      out.write("    	   \r\n");
      out.write("        /* 비밀번호 유효성 검사 */\r\n");
      out.write("        if(pw == \"\"){\r\n");
      out.write("            $('.final_pw_ck').css('display','block');\r\n");
      out.write("            pwCheck = false;\r\n");
      out.write("        }else{\r\n");
      out.write("            $('.final_pw_ck').css('display', 'none');\r\n");
      out.write("            pwCheck = true;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* 비밀번호 확인 유효성 검사 */\r\n");
      out.write("        if(pwck == \"\"){\r\n");
      out.write("            $('.final_pwck_ck').css('display','block');\r\n");
      out.write("            pwckCheck = false;\r\n");
      out.write("        }else{\r\n");
      out.write("            $('.final_pwck_ck').css('display', 'none');\r\n");
      out.write("            pwckCheck = true;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 이름 유효성 검사 */\r\n");
      out.write("        if(name == \"\"){\r\n");
      out.write("            $('.final_name_ck').css('display','block');\r\n");
      out.write("            nameCheck = false;\r\n");
      out.write("        }else{\r\n");
      out.write("            $('.final_name_ck').css('display', 'none');\r\n");
      out.write("            nameCheck = true;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 이메일 유효성 검사 */\r\n");
      out.write("        if(mail == \"\"){\r\n");
      out.write("            $('.final_mail_ck').css('display','block');\r\n");
      out.write("            mailCheck = false;\r\n");
      out.write("        }else{\r\n");
      out.write("            $('.final_mail_ck').css('display', 'none');\r\n");
      out.write("            mailCheck = true;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* 주소 유효성 검사 */\r\n");
      out.write("        if(addr == \"\"){\r\n");
      out.write("            $('.final_addr_ck').css('display','block');\r\n");
      out.write("            addressCheck = false;\r\n");
      out.write("        }else{\r\n");
      out.write("            $('.final_addr_ck').css('display', 'none');\r\n");
      out.write("            addressCheck = true;\r\n");
      out.write("        }\r\n");
      out.write("        /* 최종 유효성 검사 */\r\n");
      out.write("        if(idCheck&&idckCheck&&pwCheck&&pwckCheck&&pwckcorCheck&&nameCheck&&mailCheck&&mailnumCheck&&addressCheck ){\r\n");
      out.write("\r\n");
      out.write("    		$(\"#join_form\").attr(\"action\", \"/member/join\");\r\n");
      out.write("    		$(\"#join_form\").submit();\r\n");
      out.write("        }   	\r\n");
      out.write("        \r\n");
      out.write("        return false;\r\n");
      out.write("    	});\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    //아이디 중복검사\r\n");
      out.write("    $('.id_input').on(\"propertychange change keyup paste input\", function(){\r\n");
      out.write("\r\n");
      out.write("    	//console.log(\"keyup 테스트\");	\r\n");
      out.write("    	\r\n");
      out.write("    	var memberId = $('.id_input').val();			// .id_input에 입력되는 값\r\n");
      out.write("    	var data = {memberId : memberId}				// '컨트롤에 넘길 데이터 이름' : '데이터(.id_input에 입력되는 값)'\r\n");
      out.write("    	\r\n");
      out.write("    	$.ajax({\r\n");
      out.write("    		type : \"post\",\r\n");
      out.write("    		url : \"/member/memberIdChk\",\r\n");
      out.write("    		data : data,\r\n");
      out.write("    		success : function(result){\r\n");
      out.write("    			if(result != 'fail'){\r\n");
      out.write("    				$('.id_input_re_1').css(\"display\",\"inline-block\");\r\n");
      out.write("    				$('.id_input_re_2').css(\"display\", \"none\");	\r\n");
      out.write("    				idckCheck = true;\r\n");
      out.write("    			} else {\r\n");
      out.write("    				$('.id_input_re_2').css(\"display\",\"inline-block\");\r\n");
      out.write("    				$('.id_input_re_1').css(\"display\", \"none\");	\r\n");
      out.write("    				idckCheck = false;\r\n");
      out.write("    			}\r\n");
      out.write("    		} // success 종료\r\n");
      out.write("    	}); // ajax 종료	\r\n");
      out.write("\r\n");
      out.write("    });// function\r\n");
      out.write("\r\n");
      out.write("    /* 인증번호 이메일 전송 */\r\n");
      out.write("    $(\".mail_check_button\").click(function(){\r\n");
      out.write("    	 var email = $(\".mail_input\").val();  \r\n");
      out.write("    	 var checkBox = $(\".mail_check_input\");\r\n");
      out.write("    	 var boxWrap = $(\".mail_check_input_box\");\r\n");
      out.write("    	var warnMsg = $(\".mail_input_box_warn\");    // 이메일 입력 경고글\r\n");
      out.write("    	 \r\n");
      out.write("\r\n");
      out.write("        /* 이메일 형식 유효성 검사 */\r\n");
      out.write("        if(mailFormCheck(email)){\r\n");
      out.write("            warnMsg.html(\"이메일이 전송 되었습니다. 이메일을 확인해주세요.\");\r\n");
      out.write("            warnMsg.css(\"display\", \"inline-block\");\r\n");
      out.write("        } else {\r\n");
      out.write("            warnMsg.html(\"올바르지 못한 이메일 형식입니다.\");\r\n");
      out.write("            warnMsg.css(\"display\", \"inline-block\");\r\n");
      out.write("            return false;\r\n");
      out.write("        }   \r\n");
      out.write("    	\r\n");
      out.write("    	 $.ajax({\r\n");
      out.write("    	        \r\n");
      out.write("    	        type:\"GET\",\r\n");
      out.write("    	        url:\"mailCheck?email=\" + email,\r\n");
      out.write("    	       success:function(data){\r\n");
      out.write("    	    	 checkBox.attr(\"disabled\",false);\r\n");
      out.write("    	    	 boxWrap.attr(\"id\",\"mail_check_input_box_true\");\r\n");
      out.write("    	    	 code = data;\r\n");
      out.write("    	       }\r\n");
      out.write("    	        		\r\n");
      out.write("    	                \r\n");
      out.write("    	    });\r\n");
      out.write("    /* 인증번호 비교 */\r\n");
      out.write("    $(\".mail_check_input\").blur(function(){\r\n");
      out.write("    	var inputCode = $(\".mail_check_input\").val();  // 입력코드  \r\n");
      out.write("    	var checkResult = $(\"#mail_check_input_box_warn\");    // 비교 결과\r\n");
      out.write("    	\r\n");
      out.write("    	 if(inputCode == code && inputCode != null ){                            // 일치할 경우\r\n");
      out.write("    	        checkResult.html(\"인증번호가 일치합니다.\");\r\n");
      out.write("    	        checkResult.attr(\"class\", \"correct\");\r\n");
      out.write("    	        mailnumCheck = true;\r\n");
      out.write("    	    } else {                                            // 일치하지 않을 경우\r\n");
      out.write("    	        checkResult.html(\"인증번호를 다시 확인해주세요.\");\r\n");
      out.write("    	        checkResult.attr(\"class\", \"incorrect\");\r\n");
      out.write("    	        mailnumCheck = false;\r\n");
      out.write("    	    }    \r\n");
      out.write("    });\r\n");
      out.write("    });\r\n");
      out.write("     \r\n");
      out.write("\r\n");
      out.write("    /* 다음 주소 연동 */\r\n");
      out.write("    function execution_daum_address(){\r\n");
      out.write("        \r\n");
      out.write("    	new daum.Postcode({\r\n");
      out.write("            oncomplete: function(data) {\r\n");
      out.write("                // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분입니다.\r\n");
      out.write("                \r\n");
      out.write("            	// 각 주소의 노출 규칙에 따라 주소를 조합한다.\r\n");
      out.write("                // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("                var addr = ''; // 주소 변수\r\n");
      out.write("                var extraAddr = ''; // 참고항목 변수\r\n");
      out.write("\r\n");
      out.write("                //사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.\r\n");
      out.write("                if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우\r\n");
      out.write("                    addr = data.roadAddress;\r\n");
      out.write("                } else { // 사용자가 지번 주소를 선택했을 경우(J)\r\n");
      out.write("                    addr = data.jibunAddress;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                // 사용자가 선택한 주소가 도로명 타입일때 참고항목을 조합한다.\r\n");
      out.write("                if(data.userSelectedType === 'R'){\r\n");
      out.write("                    // 법정동명이 있을 경우 추가한다. (법정리는 제외)\r\n");
      out.write("                    // 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\r\n");
      out.write("                    if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){\r\n");
      out.write("                        extraAddr += data.bname;\r\n");
      out.write("                    }\r\n");
      out.write("                    // 건물명이 있고, 공동주택일 경우 추가한다.\r\n");
      out.write("                    if(data.buildingName !== '' && data.apartment === 'Y'){\r\n");
      out.write("                        extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);\r\n");
      out.write("                    }\r\n");
      out.write("                    // 표시할 참고항목이 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.\r\n");
      out.write("                    if(extraAddr !== ''){\r\n");
      out.write("                        extraAddr = ' (' + extraAddr + ')';\r\n");
      out.write("                    }\r\n");
      out.write("    	                // 주소변수 문자열과 참고항목 문자열 합치기\r\n");
      out.write("    	                addr += extraAddr;\r\n");
      out.write("    	            \r\n");
      out.write("                } else {\r\n");
      out.write("                   addr += ' ';\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                // 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("                $(\".address_input_1\").val(data.zonecode);\r\n");
      out.write("                $(\".address_input_2\").val(addr);\r\n");
      out.write("           \r\n");
      out.write("             // 상세주소 입력란 disabled 속성 변경 및 커서를 상세주소 필드로 이동한다.\r\n");
      out.write("                $(\".address_input_3\").attr(\"readonly\",false);\r\n");
      out.write("                 $(\".address_input_3\").focus();\r\n");
      out.write("     \r\n");
      out.write("            }\r\n");
      out.write("        }).open();    \r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* 비밀번호 확인 일치 유효성 검사 */\r\n");
      out.write("\r\n");
      out.write("    $('.pwck_input').on(\"propertychange change keyup paste input\", function(){\r\n");
      out.write("    	 var pw = $('.pw_input').val();\r\n");
      out.write("    	    var pwck = $('.pwck_input').val();\r\n");
      out.write("    	    $('.final_pwck_ck').css('display', 'none');\r\n");
      out.write("    	    \r\n");
      out.write("    	    if(pw == pwck){\r\n");
      out.write("    	        $('.pwck_input_re_1').css('display','block');\r\n");
      out.write("    	        $('.pwck_input_re_2').css('display','none');\r\n");
      out.write("    	        pwckcorCheck = true;\r\n");
      out.write("    	    }else{\r\n");
      out.write("    	        $('.pwck_input_re_1').css('display','none');\r\n");
      out.write("    	        $('.pwck_input_re_2').css('display','block');\r\n");
      out.write("    	        pwckcorCheck = false;\r\n");
      out.write("    	    }        \r\n");
      out.write("        \r\n");
      out.write("    });    \r\n");
      out.write("\r\n");
      out.write("    /* 입력 이메일 형식 유효성 검사 */\r\n");
      out.write("    function mailFormCheck(email){\r\n");
      out.write("    		 var form = /^([\\w-]+(?:\\.[\\w-]+)*)@((?:[\\w-]+\\.)*\\w[\\w-]{0,66})\\.([a-z]{2,6}(?:\\.[a-z]{2})?)$/i;\r\n");
      out.write("    		 return form.test(email);\r\n");
      out.write("    }\r\n");
      out.write("     \r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/member/join.jsp(107,11) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("          <li class=\"nav-item\">\r\n");
          out.write("          \r\n");
          out.write("            <a href=\"/member/login\" class=\"nav-link border border-light rounded waves-effect\">\r\n");
          out.write("             LogIn\r\n");
          out.write("            </a>\r\n");
          out.write("          </li>\r\n");
          out.write("          <li class=\"nav-item\">\r\n");
          out.write("            <a href=\"/member/join\" class=\"nav-link border border-light rounded waves-effect\"\r\n");
          out.write("              >\r\n");
          out.write("             Join us\r\n");
          out.write("            </a>\r\n");
          out.write("          </li>\r\n");
          out.write("           ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/member/join.jsp(121,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member != null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" \r\n");
          out.write("           	\r\n");
          out.write("           	\r\n");
          out.write("           		<div class=\"nav-link border border-light rounded waves-effect\">\r\n");
          out.write("           			<span>충전 금액 : ");
          if (_jspx_meth_fmt_005fformatNumber_005f0(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write(" </span>\r\n");
          out.write("           			<span>포인트 : ");
          if (_jspx_meth_fmt_005fformatNumber_005f1(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("</span>\r\n");
          out.write("           		</div>\r\n");
          out.write("            ");
          if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("             <a href=\"/member/logout.do\" class=\"nav-link border border-light rounded waves-effect\">Logout</a>\r\n");
          out.write("            \r\n");
          out.write("           ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/member/join.jsp(125,28) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.money}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/member/join.jsp(125,28) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setPattern("#,###");
      int _jspx_eval_fmt_005fformatNumber_005f0 = _jspx_th_fmt_005fformatNumber_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f0);
      _jspx_th_fmt_005fformatNumber_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f1_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f1.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/member/join.jsp(126,26) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.point }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/member/join.jsp(126,26) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f1.setPattern("#,###");
      int _jspx_eval_fmt_005fformatNumber_005f1 = _jspx_th_fmt_005fformatNumber_005f1.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f1);
      _jspx_th_fmt_005fformatNumber_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f1, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/member/join.jsp(128,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.adminCk == 1 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("            <a href=\"/admin/main\" class=\"nav-link border border-light rounded waves-effect\">AdminPage</a>\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }
}
