/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.83
 * Generated at: 2023-01-13 07:15:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class productEnroll_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("    <title>Admin Page</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom fonts for this template-->\r\n");
      out.write("    <link href=\"/resources/css/vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <link\r\n");
      out.write("        href=\"https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i\"\r\n");
      out.write("        rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom styles for this template-->\r\n");
      out.write("   <script src=\"https://kit.fontawesome.com/8a241b3425.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <link href=\"/resources/css/admin/sb-admin-2.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"/resources/css/admin/productEnroll.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("	<script\r\n");
      out.write("	  src=\"https://code.jquery.com/jquery-3.4.1.js\"\r\n");
      out.write("	  integrity=\"sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=\"\r\n");
      out.write("	  crossorigin=\"anonymous\"></script>\r\n");
      out.write("	  \r\n");
      out.write("	  \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body id=\"page-top\">\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <!-- Page Wrapper -->\r\n");
      out.write("    <div id=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("       <!-- Sidebar -->\r\n");
      out.write("        <ul class=\"navbar-nav bg-gradient-primary sidebar sidebar-dark\" id=\"accordionSidebar\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Sidebar - Brand -->\r\n");
      out.write("            <li>\r\n");
      out.write("            <a class=\"sidebar-brand justify-content-center\" href=\"/main\">\r\n");
      out.write("                <div class=\"sidebar-brand-icon\">\r\n");
      out.write("                    <i class=\"fas fa-laugh-wink\"></i>\r\n");
      out.write("                <div class=\"sidebar-brand-text\">Star Coffee </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </a>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("            <!-- Divider -->\r\n");
      out.write("            <li>\r\n");
      out.write("            <hr class=\"sidebar-divider\">\r\n");
      out.write("		</li>\r\n");
      out.write("            <!-- Heading -->\r\n");
      out.write("            \r\n");
      out.write("            <li><div class=\"sidebar-heading\">\r\n");
      out.write("                <span>상품 관리</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            <!-- Nav Item - Pages Collapse Menu -->\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link collapsed\" href=\"/admin/productManage\"  >\r\n");
      out.write("                    <i class=\"fa-solid fa-bars\"></i>\r\n");
      out.write("                    <span>상품 목록</span>\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            <!-- Nav Item - Utilities Collapse Menu -->\r\n");
      out.write("            <li class=\"nav-item active\">\r\n");
      out.write("                <a class=\"nav-link collapsed\" href=\"/admin/productEnroll\">\r\n");
      out.write("                    <i class=\"fas fa-fw fa-plus\"></i>\r\n");
      out.write("                    <span>상품등록</span>\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("			\r\n");
      out.write("\r\n");
      out.write("            <!-- Nav Item - Tables -->\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"/orderList\">\r\n");
      out.write("                    <i class=\"fas fa-fw fa-table\"></i>\r\n");
      out.write("                    <span>주문 관리</span></a>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("           \r\n");
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("        <!-- End of Sidebar -->\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        <!-- Content Wrapper -->\r\n");
      out.write("        <div id=\"content-wrapper\" class=\"d-flex flex-column\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Main Content -->\r\n");
      out.write("            <div id=\"content\">\r\n");
      out.write("\r\n");
      out.write("                <!-- Topbar -->\r\n");
      out.write("                <nav class=\"navbar\">\r\n");
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("\r\n");
      out.write("                    <!-- Topbar Navbar -->\r\n");
      out.write("                    <span class=\" d-none d-lg-inline text-gray-600 small\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.memberName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("님 환영합니다. </span> \r\n");
      out.write("                    <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("\r\n");
      out.write("                        <li class=\"nav-item dropdown no-arrow\">\r\n");
      out.write("                            <a class=\"nav-link dropdown-toggle\" href=\"/member/logout.do\" id=\"userDropdown\">\r\n");
      out.write("                                <span class=\" d-none d-lg-inline text-gray-600 small\">Logout</span>    \r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("\r\n");
      out.write("                    </ul>\r\n");
      out.write("\r\n");
      out.write("                </nav>\r\n");
      out.write("                <!-- End of Topbar -->\r\n");
      out.write("\r\n");
      out.write("                <!-- Begin Page Content -->\r\n");
      out.write("                <div class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("                    <!-- Page Heading -->\r\n");
      out.write("\r\n");
      out.write("                <div class=\"admin_content_wrap\">\r\n");
      out.write("                    <div class=\"admin_content_subject\"><span>상품 등록</span></div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"admin_content_main\">\r\n");
      out.write("                    	<form action=\"/admin/productEnroll\" method=\"post\" id=\"enrollForm\">\r\n");
      out.write("                    		<div class=\"form_section\">\r\n");
      out.write("                    			<div class=\"form_section_title\">\r\n");
      out.write("                    				<label>상품명</label>\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    			<div class=\"form_section_content\">\r\n");
      out.write("                    				<input name=\"productName\">\r\n");
      out.write("                    				<span id=\"warn_productName\">제품명을 입력해주세요.</span>\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    		</div>\r\n");
      out.write("                    		\r\n");
      out.write("                    		\r\n");
      out.write("                    		\r\n");
      out.write("                    		\r\n");
      out.write("                    		<div class=\"form_section\">\r\n");
      out.write("                    			<div class=\"form_section_title\">\r\n");
      out.write("                    				<label>상품가격</label>\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    			<div class=\"form_section_content\">\r\n");
      out.write("                    				<input name=\"productPrice\">\r\n");
      out.write("                    				<span id=\"warn_productPrice\">제품가격을 입력해주세요.</span>\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    		</div>\r\n");
      out.write("                    		\r\n");
      out.write("                    		\r\n");
      out.write("                    		\r\n");
      out.write("                    		<div class=\"form_section\">\r\n");
      out.write("                    			<div class=\"form_section_title\">\r\n");
      out.write("                    				<label>카테고리</label>\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    			<div class=\"form_section_content\">\r\n");
      out.write("                    				<div class =\"cate_wrap\">\r\n");
      out.write("                    				<select class=\"cate1\" name=\"categoryId\">\r\n");
      out.write("                    					<option selected value =\"none\">선택</option>            					\r\n");
      out.write("                    				</select>\r\n");
      out.write("                    				</div>\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    			<div class=\"form_section_content\">\r\n");
      out.write("                    				<div class =\"cate_wrap\">\r\n");
      out.write("                    				<select class=\"cate2\" name =\"cateCode\">\r\n");
      out.write("                    					<option selected value=\"none\">선택 </option>                    					\r\n");
      out.write("                    				</select>\r\n");
      out.write("                    				<span id=\"warn_cateCode\">카테고리를 선택해주세요.</span>\r\n");
      out.write("                    				</div>\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    			\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    	\r\n");
      out.write("                    		<div class=\"form_section\">\r\n");
      out.write("                    			<div class=\"form_section_title\">\r\n");
      out.write("                    				<label>상품 이미지</label>\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    			<div class=\"form_section_content\">\r\n");
      out.write("									<input type=\"file\" id =\"fileItem\" name='uploadFile' style=\"height: 50px;\">\r\n");
      out.write("									<div id=\"uploadResult\">\r\n");
      out.write("									\r\n");
      out.write("									</div>\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    		</div>  \r\n");
      out.write("                    		\r\n");
      out.write("                    		\r\n");
      out.write("                    		<div class=\"form_section\">\r\n");
      out.write("                    			<div class=\"form_section_title\">\r\n");
      out.write("                    				<label>상품정보</label>\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    			<div class=\"form_section_content\">\r\n");
      out.write("                    				<input name=\"productInfo\" type=\"text\">\r\n");
      out.write("                    				<span id=\"warn_productInfo\">제품소개를 입력해주세요.</span>\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    		</div>\r\n");
      out.write("                  \r\n");
      out.write("                  \r\n");
      out.write("                    	</form>\r\n");
      out.write("                   			<div class=\"btn_section\">\r\n");
      out.write("                   				<button id=\"cancelBtn\" class=\"btn\">취 소</button>\r\n");
      out.write("	                    		<button id=\"enrollBtn\" class=\"btn enroll_btn\">등 록</button>\r\n");
      out.write("	                    	</div> \r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <!-- /. -->\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- End of Main Content -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- End of Content Wrapper -->\r\n");
      out.write("            <!-- Footer -->\r\n");
      out.write("            <footer class=\"sticky-footer bg-white\">\r\n");
      out.write("                <div class=\"container my-auto\">\r\n");
      out.write("                    <div class=\"copyright text-center my-auto\">\r\n");
      out.write("                        <span>Copyright &copy; Kim Young Hwan 2022 - 2023</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </footer>\r\n");
      out.write("            <!-- End of Footer -->\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- End of Page Wrapper -->\r\n");
      out.write("</div>\r\n");
      out.write("    <!-- Scroll to Top Button-->\r\n");
      out.write("    <a class=\"scroll-to-top rounded\" href=\"#page-top\">\r\n");
      out.write("        <i class=\"fas fa-angle-up\"></i>\r\n");
      out.write("    </a>\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap core JavaScript-->\r\n");
      out.write("    <script src=\"/resources/css/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/css/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Core plugin JavaScript-->\r\n");
      out.write("    <script src=\"/resources/css/vendor/jquery-easing/jquery.easing.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom scripts for all pages-->\r\n");
      out.write("    <script src=\"/resources/js/sb-admin-2.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write(" 	let enrollForm = $(\"#enrollForm\")\r\n");
      out.write(" 	\r\n");
      out.write("/* 이미지 업로드 */\r\n");
      out.write("$(\"input[type='file']\").on(\"change\", function(e){\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	/*이미지 존재시 삭제*/\r\n");
      out.write("	if($(\".imgDeleteBtn\").length > 0){\r\n");
      out.write("		console.log(\"이미지삭제\");\r\n");
      out.write("		deleteFile();\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	let formData = new FormData();\r\n");
      out.write("	let fileInput = $('input[name=\"uploadFile\"]');\r\n");
      out.write("	let fileList = fileInput[0].files;\r\n");
      out.write("	let fileObj = fileList[0];\r\n");
      out.write("	\r\n");
      out.write("	console.log(\"fileList::::: \"+ fileList);\r\n");
      out.write("	console.log(\"fileObj::::\" + fileObj);\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	if(!fileCheck(fileObj.name, fileObj.size)){\r\n");
      out.write("		return false;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	formData.append(\"uploadFile\", fileObj);\r\n");
      out.write("\r\n");
      out.write("$.ajax({\r\n");
      out.write("	url: '/admin/uploadAjaxAction',\r\n");
      out.write("	processData : false,\r\n");
      out.write("	contentType : false,\r\n");
      out.write("	data : formData,\r\n");
      out.write("	type : 'POST',\r\n");
      out.write("	dataType : 'json',\r\n");
      out.write("	success : function(result){\r\n");
      out.write("		console.log(result);\r\n");
      out.write("		showUploadImage(result);\r\n");
      out.write("	},\r\n");
      out.write("	error : function(result){\r\n");
      out.write("		alert(\"이미지 파일이 아닙니다.\");\r\n");
      out.write("	}\r\n");
      out.write("});\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("/* var, method related with attachFile */\r\n");
      out.write("let regex = new RegExp(\"(.*?)\\.(jpg|png|jpeg)$\");\r\n");
      out.write("let maxSize = 5242880; 	\r\n");
      out.write("\r\n");
      out.write("function fileCheck(fileName, fileSize){\r\n");
      out.write("\r\n");
      out.write("	if(fileSize >= maxSize){\r\n");
      out.write("		alert(\"파일 용량이 너무 큽니다.\");\r\n");
      out.write("		return false;\r\n");
      out.write("	}\r\n");
      out.write("		  \r\n");
      out.write("	if(!regex.test(fileName)){\r\n");
      out.write("		alert(\"해당 종류의 파일은 업로드할 수 없습니다.\");\r\n");
      out.write("		return false;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	return true;		\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//이미지 출력\r\n");
      out.write("function showUploadImage(uploadResultArr){\r\n");
      out.write("	\r\n");
      out.write("		//전달받은 데이터 검증\r\n");
      out.write("		if(!uploadResultArr || uploadResultArr.length == 0	){return}\r\n");
      out.write("		\r\n");
      out.write("		let uploadResult = $(\"#uploadResult\");\r\n");
      out.write("		\r\n");
      out.write("		let obj = uploadResultArr[0];\r\n");
      out.write("		\r\n");
      out.write("		let str = \"\";\r\n");
      out.write("		\r\n");
      out.write("		let fileCallPath = encodeURIComponent(obj.uploadPath.replace(/\\\\/g, '/') + \"/s_\" + obj.uuid + \"_\" + obj.fileName);\r\n");
      out.write("		\r\n");
      out.write("		str += \"<div id = 'result_card>\";\r\n");
      out.write("		str += \"<img src='/display?fileName=\" + fileCallPath +\"'>\";\r\n");
      out.write("		str += \"<div class='imgDeleteBtn' data-file='\" + fileCallPath + \"'>x</div>\";\r\n");
      out.write("		str += \"<input type='hidden' name='imageList[0].fileName' value='\"+ obj.fileName +\"'>\";\r\n");
      out.write("		str += \"<input type='hidden' name='imageList[0].uuid' value='\"+ obj.uuid +\"'>\";\r\n");
      out.write("		str += \"<input type='hidden' name='imageList[0].uploadPath' value='\"+ obj.uploadPath +\"'>\";\r\n");
      out.write("		str += \"</div>\";\r\n");
      out.write("		\r\n");
      out.write("		console.log(\"str:::::::: \" + str);\r\n");
      out.write("		uploadResult.append(str);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//이미지 삭제 버튼\r\n");
      out.write("\r\n");
      out.write("$(\"#uploadResult\").on(\"click\",\".imgDeleteBtn\", function(e){\r\n");
      out.write("	deleteFile();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("/* 파일 삭제 메서드 */\r\n");
      out.write("function deleteFile(){\r\n");
      out.write("	\r\n");
      out.write("	let targetFile = $(\".imgDeleteBtn\").data(\"file\");\r\n");
      out.write("	\r\n");
      out.write("	let targetDiv = $(\"#result_card\");\r\n");
      out.write("	\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		url: '/admin/deleteFile',\r\n");
      out.write("		data : {fileName : targetFile},\r\n");
      out.write("		dataType : 'text',\r\n");
      out.write("		type : 'POST',\r\n");
      out.write("		success : function(result){\r\n");
      out.write("			console.log(result);\r\n");
      out.write("			\r\n");
      out.write("			targetDiv.remove();\r\n");
      out.write("			$(\"input[type='file']\").val(\"\");\r\n");
      out.write("			\r\n");
      out.write("		},\r\n");
      out.write("		error : function(result){\r\n");
      out.write("			console.log(result);\r\n");
      out.write("			\r\n");
      out.write("			alert(\"파일을 삭제하지 못하였습니다.\")\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(" 	\r\n");
      out.write(" 	/* 취소 버튼 */\r\n");
      out.write("$(\"#cancelBtn\").click(function(){\r\n");
      out.write("    location.href=\"/admin/productManage\"\r\n");
      out.write("});\r\n");
      out.write("	\r\n");
      out.write(" 	\r\n");
      out.write(" 	 \r\n");
      out.write(" 	/* 등록 버튼 */\r\n");
      out.write(" 	$(\"#enrollBtn\").click(function(e){    \r\n");
      out.write(" 		\r\n");
      out.write(" 		e.preventDefault();\r\n");
      out.write(" 		\r\n");
      out.write(" 		//공백 확인\r\n");
      out.write(" 		let nameCheck = false;\r\n");
      out.write(" 		let categoryCheck = false;\r\n");
      out.write(" 		let infoCheck = false;\r\n");
      out.write(" 		let priceCheck = false;\r\n");
      out.write(" 		let cateCodeCheck = false;\r\n");
      out.write(" 		\r\n");
      out.write(" 		\r\n");
      out.write(" 		let productName = $('input[name=productName]').val();\r\n");
      out.write(" 		let productPrice = $('input[name=productPrice]').val();\r\n");
      out.write(" 		let categoryId = $('select[name=categoryId]').val();\r\n");
      out.write(" 		let productInfo = $('input[name=productInfo]').val();\r\n");
      out.write(" 		let cateCode = $('select[name=cateCode]').val();\r\n");
      out.write(" 		\r\n");
      out.write(" 		\r\n");
      out.write(" 		\r\n");
      out.write(" 		let wProductName = $('#warn_productName');\r\n");
      out.write(" 		let wProductPrice = $('#warn_productPrice');\r\n");
      out.write(" 		let wCategoryId = $('#warn_categoryId');\r\n");
      out.write(" 		let wProductInfo = $('#warn_productInfo');\r\n");
      out.write(" 		let wCateCode = $('#warn_cateCode');\r\n");
      out.write(" 		//이름 공란 체크\r\n");
      out.write(" 		if(productName ===''){\r\n");
      out.write(" 			wProductName.css('display', 'block');\r\n");
      out.write(" 			nameCheck = false;\r\n");
      out.write(" 			\r\n");
      out.write(" 		}else {\r\n");
      out.write(" 			wProductName.css('display','none');\r\n");
      out.write(" 			nameCheck = true;\r\n");
      out.write(" 		}\r\n");
      out.write(" 		\r\n");
      out.write(" 		//가격 체크\r\n");
      out.write(" 		if(productPrice === ''){\r\n");
      out.write(" 			wProductPrice.css('display','block');\r\n");
      out.write(" 			priceCheck = false;\r\n");
      out.write(" 		}else {\r\n");
      out.write(" 			wProductPrice.css('display','none');\r\n");
      out.write(" 			priceCheck = true;\r\n");
      out.write(" 		}\r\n");
      out.write(" 		\r\n");
      out.write(" 		//카테고리 체크\r\n");
      out.write(" 		if(categoryId ==='none'){\r\n");
      out.write(" 			wCategoryId.css('display','block');\r\n");
      out.write(" 			categoryCheck = false;\r\n");
      out.write(" 		} else{\r\n");
      out.write(" 			wCategoryId.css('display', 'none');\r\n");
      out.write(" 			categoryCheck = true;\r\n");
      out.write(" 		}\r\n");
      out.write(" 		\r\n");
      out.write(" 		\r\n");
      out.write(" 		//카테코드 체크\r\n");
      out.write(" 		if(cateCode === 'none'){\r\n");
      out.write(" 			wCateCode.css('display','block');\r\n");
      out.write(" 			cateCodeCheck = false;\r\n");
      out.write(" 		} else{\r\n");
      out.write(" 			wCateCode.css('display','none');\r\n");
      out.write(" 			cateCodeCheck = true;\r\n");
      out.write(" 		}\r\n");
      out.write(" 		//제품소개 체크\r\n");
      out.write(" 		if(productInfo ===''){\r\n");
      out.write(" 			wProductInfo.css('display', 'block');\r\n");
      out.write(" 			infoCheck = false;\r\n");
      out.write(" 		}else{\r\n");
      out.write(" 			wProductInfo.css('display','none');\r\n");
      out.write(" 			infoCheck = true;\r\n");
      out.write(" 		}\r\n");
      out.write(" 		\r\n");
      out.write(" 		//최종검사\r\n");
      out.write(" 		if(nameCheck && priceCheck && categoryCheck && infoCheck &&cateCodeCheck){\r\n");
      out.write(" 			\r\n");
      out.write(" 		\r\n");
      out.write(" 	  enrollForm.submit();		\r\n");
      out.write(" 		}	else{\r\n");
      out.write(" 		\r\n");
      out.write(" 			return false;\r\n");
      out.write(" 		}\r\n");
      out.write(" 	    \r\n");
      out.write(" 	});\r\n");
      out.write(" 	\r\n");
      out.write(" 	\r\n");
      out.write("	//카테고리\r\n");
      out.write("	let cateList = JSON.parse('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cateList}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("');\r\n");
      out.write("	let cate1Array = new Array();\r\n");
      out.write("	let cate2Array = new Array();\r\n");
      out.write("	let cate1Obj = new Object();\r\n");
      out.write("	let cate2Obj = new Object();\r\n");
      out.write("	\r\n");
      out.write("	let cateSelect1 = $(\".cate1\");\r\n");
      out.write("	let cateSelect2 = $(\".cate2\");\r\n");
      out.write("	\r\n");
      out.write("	//카테고리 배열 초기화\r\n");
      out.write("	function makeCateArray(obj,array,cateList,tier){\r\n");
      out.write("		for(let i = 0; i < cateList.length; i++){\r\n");
      out.write("			if(cateList[i].tier === tier){\r\n");
      out.write("				\r\n");
      out.write("			obj = new Object();\r\n");
      out.write("			\r\n");
      out.write("			obj.cateName = cateList[i].cateName;\r\n");
      out.write("			obj.cateCode = cateList[i].cateCode;\r\n");
      out.write("			obj.cateParent = cateList[i].cateParent;\r\n");
      out.write("			\r\n");
      out.write("			array.push(obj);\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("	//배열 초기화\r\n");
      out.write("	makeCateArray(cate1Obj,cate1Array , cateList,1);\r\n");
      out.write("	makeCateArray(cate2Obj,cate2Array , cateList,2);  \r\n");
      out.write("	\r\n");
      out.write("	//대분류 <Option> 태그\r\n");
      out.write("	for(let i = 0; i < cate1Array.length; i++){\r\n");
      out.write("		cateSelect1.append(\"<option value='\"+cate1Array[i].cateCode+\"'>\"+ cate1Array[i].cateName + \"</option>\");\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	//중분류 태그\r\n");
      out.write("	$(cateSelect1).on(\"change\",function(){\r\n");
      out.write("		let selectVal1 = $(this).find(\"option:selected\").val();\r\n");
      out.write("		cateSelect2.children().remove();\r\n");
      out.write("		cateSelect2.append(\"<option value='none'>선택</option>\")\r\n");
      out.write("	\r\n");
      out.write("		for(let i = 0; i < cate2Array.length; i++){\r\n");
      out.write("			if(selectVal1 === cate2Array[i].cateParent){\r\n");
      out.write("				cateSelect2.append(\"<option value='\"+cate2Array[i].cateCode+\"'>\" + cate2Array[i].cateName + \"</option>\");\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
